#! /bin/sh


bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true



bspc monitor -d 1 2 3 4 5  

#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc desktop II -l monocle
bspc rule -a Chromium desktop=^4 follow=on 
bspc rule -a Firefox desktop=^2 follow=on 
bspc rule -a Places floating=on 
bspc rule -a Browser floating=on 
#bspc rule -a Navigator floating=on 
#bspc rule -a Firefox desktop=^2 follow=on floating=on
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


#if ps aux | grep [p]anel > /dev/null
#then	
#	pkill panel && panel &
#else
#	panel & 
#fi
#


export PANEL_FIFO="/tmp/panel-fifo"

panel &

dunst & 

sh /home/trench/.fehbg &

urxvtd -q -f -o &

xsetroot -cursor_name left_ptr




